.TH "SPLATD" "8" 
.SH "NAME" 
splatd \(em Scalable Periodic LDAP Attribute Transmogrifier 
.SH "SYNOPSIS" 
.PP 
\fBsplatd\fR [\fB-h\fP]  [\fB-d\fP]  [\fB-f \fIconfig\fR\fP]  [\fB-p \fIpidfile\fR\fP]  
.SH "DESCRIPTION" 
.PP 
Splat is a daemon designed to help keep information in an LDAP 
directory in sync with information outside of an LDAP directory. This 
information can be any set of attributes on any object in the LDAP 
directory. 
.SH "OPTIONS" 
.IP "\fB-h\fP" 10 
Show summary of options. 
.IP "\fB-d\fP" 10 
Debug mode. Will not fork and run in the background. 
.IP "\fB-f\fP" 10 
Splat configuration file (e.g. /etc/splat-ldap/splat.conf). 
.IP "\fB-p\fP" 10 
File to write daemon pid to (e.g. /var/run/splatd.pid). 
.SH "SEE ALSO" 
.PP 
The Splat web site at http://dpw.threerings.net/projects/splat/. A manual is
available on this site, or in /usr/share/doc/splat-ldap/html. An example
configuration file can be found in
/usr/share/doc/splat-ldap/examples/splat.conf.gz.
.SH "AUTHOR" 
.PP 
This manual page was written by Nick Barkas <snb@threerings.net> for the
\fBUbuntu\fP and \fBDebian\fP systems (but may be used by others).  Permission
is granted to copy, distribute and/or modify this document under the terms of
the license at /usr/share/doc/splat-ldap/copyright.
 
.\" created by instant / docbook-to-man, Mon 12 Jun 2006, 18:44 
