#!/bin/sh
CONFIGFILE=/etc/splat-ldap/splat.conf
set -e
. /usr/share/debconf/confmodule

# Get values from the debconf db.
db_get splat-ldap/uri
uri="$RET"
db_get splat-ldap/basedn
basedn="$RET"

# Set values where variables live in the config file.
sed -e "s|@URI@|$uri|" -e "s|@BASEDN@|$basedn|g" < $CONFIGFILE > $CONFIGFILE.tmp
mv -f $CONFIGFILE.tmp $CONFIGFILE

